"""Signal polarity: which side of a binary market is the bullish signal.

For each (question, symbol) pair, polarity answers: *"if this market resolves
YES, is that bullish or bearish for a LONG position in this symbol?"* The book
is always long-only in equities; polarity only decides how the probability
path is read. "Military action against Iran ends by April 20?" is bearish oil,
so for USO the tradable signal is P(NO) = 1 - P(YES) and the path is flipped.

Three states (v2 — the old system was binary):
  +1  the YES side is the bullish signal (raw path).
  -1  the NO side is the bullish signal (path flipped, 1 - p).
   0  neither side has a clean bullish reading for this symbol — the pair is
      not tradable and the simulator skips it. A +1 label already implies "NO
      is uninformative, simply never enter"; 0 is reserved for pairs where no
      side is clean ("Will the Fed cut rates?" → NO could mean hold OR hike).
      Only the LLM labels and hand overrides can assign 0; the regex fallback
      stays binary.

Resolution precedence: override > llm > regex. A hand-verified domain fact
beats the LLM, and the LLM beats the keyword fallback. Labels live in
`data/polarity_labels.json` (generated by `ingest/label_polarity.py`, committed
so results reproduce). Run `python -m diagnostics.polarity_audit` to eyeball
every -1/0 classification before trusting a run.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

# ── Regex fallback ────────────────────────────────────────────────────────────
#
# Each rule below toggles the sign, so composition works: "Will inflation not be
# above 2.5%?" fires R1 and R3 and lands back on +1 (YES = tame inflation =
# bullish).
#
# This is a keyword heuristic, and keyword heuristics are exactly what caused
# the original bug. Known unresolved gap: `above` is subject-dependent
# ("Robinhood subscribers above 4.2M" is bullish, "annual inflation above 2.5%"
# is bearish, "OPEC production above 18M bpd" is bearish for the USO it maps
# to). R3/R4 encode the two bearish subjects present in the current universe; a
# new subject will need a new rule, or the LLM polarity pass.

# R1 -- explicit negation of the event.
_NEG_RE = re.compile(r"^\s*no\b|\bnot\b|\bnever\b|\bwithout\b|\brefrains?\s+from\b", re.I)

# R2 -- the event ceases / reverses. `\bends?\b` must not fire on "by end of May",
# which is a date, not a cessation.
_CESSATION_RE = re.compile(
    r"\bends?\b(?!\s+of\b)|\bending\b(?!\s+of\b)"
    r"|\bceasefire\b|\bde-?escalat\w*|\bwithdraw\w*|\breturns?\s+to\s+normal\b",
    re.I,
)

# R3 -- a macro level rising is bearish for equities.
_MACRO_UP_RE = re.compile(r"\babove\b|\bexceeds?\b|\bhikes?\b|\braises?\b", re.I)
_MACRO_SUBJ_RE = re.compile(r"\binflation\b|\bcpi\b|\brates?\b", re.I)

# R4 -- more commodity supply is bearish for the commodity's long proxy. The
# commodity context is required: "Tractor Supply (TSCO)" is a retailer, and
# without the guard "Will Tractor Supply rise above $300?" would flip to -1.
_SUPPLY_UP_RE = re.compile(r"\babove\b|\bexceeds?\b|\brises?\b|\bincreases?\b", re.I)
_SUPPLY_SUBJ_RE = re.compile(r"\bproduction\b|\boutput\b|\bsupply\b", re.I)
_COMMODITY_RE = re.compile(r"\bcrude\b|\boil\b|\bopec\b|\bbarrels?\b|\bnatural\s+gas\b|\bgas\b", re.I)

# R5 -- an adverse corporate/market event. Note "below" is deliberately absent:
# it would match the company "Five Below (FIVE)".
_BEARISH_EVENT_RE = re.compile(
    r"\bmiss(?:es|ed)?\b|\bfalls?\b|\bfallen\b|\bdeclin\w*|\bcrash\w*"
    r"|\bfails?\s+to\b|\brejects?\b|\bdowngrade\w*|\bbankrupt\w*"
    r"|\bdefaults?\b|\blayoffs?\b",
    re.I,
)

_POLARITY_RULES = (
    ("R1_negation", lambda q: bool(_NEG_RE.search(q))),
    ("R2_cessation", lambda q: bool(_CESSATION_RE.search(q))),
    ("R3_macro_level_up", lambda q: bool(_MACRO_UP_RE.search(q) and _MACRO_SUBJ_RE.search(q))),
    (
        "R4_commodity_supply_up",
        lambda q: bool(
            _SUPPLY_UP_RE.search(q) and _SUPPLY_SUBJ_RE.search(q) and _COMMODITY_RE.search(q)
        ),
    ),
    ("R5_bearish_event", lambda q: bool(_BEARISH_EVENT_RE.search(q))),
)


def explain_polarity(question: str) -> tuple[int, list[str]]:
    """Regex-only polarity: (sign, names of rules that fired).

    This is the *fallback*, used for research pairs with no LLM label. Binary
    by construction (never 0).
    Prefer `resolve_polarity`.
    """
    q = (question or "").strip()
    fired = [name for name, test in _POLARITY_RULES if test(q)]
    return (-1 if len(fired) % 2 else 1), fired


# ── LLM labels, and the domain facts the LLM gets wrong ──────────────────────
#
# `ingest/label_polarity.py` asks Gemini, per (question, symbol) pair, which
# resolution (YES / NO / NEITHER) is clearly bullish for a LONG position in the
# symbol. That is a causal question about the asset, which no regex can answer.
# The families the rules cannot express:
#   - "...blockade of the Strait of Hormuz has been LIFTED by June 21"  (no rule)
#   - "US inflation >0.1% from July to August"   (R3 matches "above", not ">")
#   - "Will J.D. Vance have a diplomatic meeting with Iran by June 30?"
#       de-escalation -> bearish crude, with zero lexical markers.
#
# But the LLM is not an oracle. It is confidently (conf=1.00) and *consistently*
# wrong about container-carrier economics: it reasons "port strike -> shipping
# disruption -> ZIM down". The opposite is true -- port congestion spikes freight
# rates and carriers rally. ZIM around the Oct 2024 ILA east-coast strike, all
# TRAIN-period data (< 2026-01-01, so no OOS leakage):
#
#       2024-09-20  $20.06     run-up into the strike
#       2024-09-30  $25.66     +28%
#       2024-10-03  $21.67     tentative deal announced
#       2024-10-04  $18.95     -12.6% in one session
#
# So a port strike is BULLISH ZIM and its ending is BEARISH. These four
# overrides encode that fact. Every entry must cite its evidence.
POLARITY_OVERRIDES: dict[tuple[str, str], int] = {
    # Container carriers gain from port congestion; see the ZIM tape above.
    ("east coast port strike ends by friday?", "ZIM"): -1,
    ("east coast port strike ends by next friday?", "ZIM"): -1,
    ("east coast port strike ends in october?", "ZIM"): -1,
    ("longshoremen east coast strike by oct 1?", "ZIM"): +1,
}

_LABELS_PATH = Path(__file__).resolve().parent.parent / "data" / "polarity_labels.json"
_LLM_LABELS: dict[tuple[str, str], int] | None = None


def _norm(question: str, symbol: str) -> tuple[str, str]:
    return (question or "").strip().lower(), (symbol or "").strip().upper()


def _llm_labels() -> dict[tuple[str, str], int]:
    global _LLM_LABELS
    if _LLM_LABELS is None:
        if _LABELS_PATH.exists():
            raw = json.loads(_LABELS_PATH.read_text(encoding="utf-8"))
            if not isinstance(raw, dict):
                raise ValueError(f"{_LABELS_PATH} must contain a JSON object")
            labels: dict[tuple[str, str], int] = {}
            for rec in raw.values():
                if not isinstance(rec, dict):
                    raise ValueError(f"{_LABELS_PATH} contains a non-object label")
                value = int(rec["polarity"])
                if value not in {-1, 0, 1}:
                    raise ValueError(
                        f"invalid polarity {value!r} in {_LABELS_PATH}; expected -1, 0, or 1"
                    )
                labels[_norm(rec["question"], rec["symbol"])] = value
            _LLM_LABELS = labels
        else:
            _LLM_LABELS = {}
    return _LLM_LABELS


def resolve_polarity(question: str, symbol: str | None = None) -> tuple[int, str]:
    """Return (polarity, source) where source is override | llm | regex.

    Polarity is +1 (trade the YES side), -1 (trade the NO side, path flipped)
    or 0 (no clean bullish side -- pair not tradable; llm/override only).

    Precedence is deliberate: a hand-verified domain fact beats the LLM, and the
    LLM beats the keyword fallback. `symbol=None` can only use the fallback,
    because polarity is a property of the (question, symbol) pair -- "OPEC
    production above 18M bpd" is bearish for USO and would be bullish for a
    producer's own stock.
    """
    if symbol is not None:
        key = _norm(question, symbol)
        if key in POLARITY_OVERRIDES:
            return POLARITY_OVERRIDES[key], "override"
        label = _llm_labels().get(key)
        if label is not None:
            return label, "llm"
    return explain_polarity(question)[0], "regex"


def question_polarity(question: str, symbol: str | None = None) -> int:
    """+1 if a YES resolution is bullish for the linked symbol, -1 if bearish,
    0 if neither side is a clean signal."""
    return resolve_polarity(question, symbol)[0]


def effective_prob_path(prob_path: list[tuple], polarity: int) -> list[tuple]:
    """Re-polarize a probability path so that "high" always means "bullish"."""
    if polarity == 1:
        return prob_path
    if polarity == -1:
        return [(t, 1.0 - v) for t, v in prob_path]
    raise ValueError("polarity 0 has no tradable probability path")


# `_market_arrays` in the numba kernel caches on `(id(probs), mkt)`, so handing
# it a freshly-built dict on every call would both defeat the cache and risk
# id-reuse collisions after GC. Memoize the effective-probs dicts per source
# `probs` identity, holding a strong reference to the source so its id cannot be
# recycled while we still key on it.
#
# Keyed by polarity as well as source, because polarity belongs to the
# (question, symbol) pair while a probability path belongs to the market: many
# markets carry more than one symbol, so two symbols could in principle disagree
# and a single dict-per-market would silently serve one of them the wrong path.
# Two dicts at most, so the kernel cache still hits.
_EFF_PROBS_CACHE: dict[tuple[int, int], tuple[dict, dict]] = {}


def _effective_probs(probs: dict, mkt: str, polarity: int) -> dict:
    """A dict view of `probs` whose `mkt` entry is corrected for `polarity`."""
    if polarity not in {-1, 1}:
        raise ValueError("polarity 0 has no tradable probability path")
    key = (id(probs), polarity)
    cached = _EFF_PROBS_CACHE.get(key)
    if cached is None or cached[0] is not probs:
        cached = (probs, {})
        _EFF_PROBS_CACHE[key] = cached
    _source, eff = cached
    if mkt not in eff:
        eff[mkt] = effective_prob_path(probs.get(mkt, []), polarity)
    return eff


def _effective_prob_surge(row, polarity: int):
    """`feat_prob_surge_since_t0` is a delta on the raw path, so it flips too."""
    if polarity not in {-1, 1}:
        raise ValueError("polarity 0 has no tradable probability surge")
    surge = row.get("feat_prob_surge_since_t0")
    if polarity == 1 or surge is None:
        return surge
    try:
        value = float(surge)
    except (TypeError, ValueError):
        return surge
    return surge if value != value else -value  # NaN passes through unchanged


# Public spellings make the helpers readable at integration sites; the private
# names preserve the validated historical API and its regression tests.
effective_probs = _effective_probs
effective_prob_surge = _effective_prob_surge


def clear_effective_probs_cache() -> None:
    """Drop only the probability-dict views used by the simulation kernel."""
    _EFF_PROBS_CACHE.clear()


def clear_polarity_caches() -> None:
    """Drop all resolver caches, including the lazily loaded label artifact."""
    global _LLM_LABELS
    clear_effective_probs_cache()
    _LLM_LABELS = None
